ECHO_LEVEL_INFO = "INFO"
ECHO_LEVEL_RUNNING = "RUNNING"
ECHO_LEVEL_ERROR = "ERROR"
ECHO_LEVEL_DEFAULT = ECHO_LEVEL_INFO

ECHO_MESSAGE_PATTERN = "{}{} {}:{} {}"

COLORS_INFO = "\033[1;93m"
COLORS_RUNNING = "\033[1;94m"
COLORS_ERROR = "\033[1;31m"
COLORS_RESET = "\033[m"

INDENT_INFO = 1
INDENT_RUNNING = 2
INDENT_ERROR = INDENT_RUNNING

INDENT_CHAR_DEFAULT = "="
INDENT_CHAR_SUFIX = ">"

MESSAGE_STARTING_TASK = "Starting {} task"
MESSAGE_FINISHED_TASK = "Finished {} task"

TASK_NAME_TEST = "TEST"
TASK_NAME_LINT = "LINT"
